on:
  push:
    branches:
      - main  # Replace with your branch name if different
  workflow_dispatch:  # This allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Update to version 3, which supports Node.js 20

      - name: Fetch LeetCode Stats
        id: fetch_leetcode
        run: |
          response=$(curl -sSf "https://leetcode-api-faisalshohag.vercel.app/Priyanshu_Bhriguvanshi/") || exit 1
          echo "$response" > leetcode_stats.json || exit 1

      - name: Update README
        run: |
          easy=$(jq '.easySolved' leetcode_stats.json)
          medium=$(jq '.mediumSolved' leetcode_stats.json)
          hard=$(jq '.hardSolved' leetcode_stats.json)
          sed -i "s/<!--leetcode-easy-->.*<!--leetcode-easy-->/<!--leetcode-easy-->${easy}<!--leetcode-easy-->/" README.md
          sed -i "s/<!--leetcode-medium-->.*<!--leetcode-medium-->/<!--leetcode-medium-->${medium}<!--leetcode-medium-->/" README.md
          sed -i "s/<!--leetcode-hard-->.*<!--leetcode-hard-->/<!--leetcode-hard-->${hard}<!--leetcode-hard-->/" README.md || exit 1

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update LeetCode stats" || exit 1
          git push || exit 1
