on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Ensure this uses Node.js 20

      - name: Fetch LeetCode Stats
        id: fetch_leetcode
        run: |
          response=$(curl -sSf "https://leetcode-api-faisalshohag.vercel.app/Priyanshu_Bhriguvanshi/") || { echo "Failed to fetch LeetCode stats"; exit 1; }
          echo "$response" > leetcode_stats.json || { echo "Failed to write LeetCode stats to file"; exit 1; }

      - name: Update README
        run: |
          easy=$(jq '.easySolved' leetcode_stats.json)
          medium=$(jq '.mediumSolved' leetcode_stats.json)
          hard=$(jq '.hardSolved' leetcode_stats.json)
          sed -i "s/<!--leetcode-easy-->.*<!--leetcode-easy-->/<!--leetcode-easy-->${easy}<!--leetcode-easy-->/" README.md || { echo "Failed to update README for easy stats"; exit 1; }
          sed -i "s/<!--leetcode-medium-->.*<!--leetcode-medium-->/<!--leetcode-medium-->${medium}<!--leetcode-medium-->/" README.md || { echo "Failed to update README for medium stats"; exit 1; }
          sed -i "s/<!--leetcode-hard-->.*<!--leetcode-hard-->/<!--leetcode-hard-->${hard}<!--leetcode-hard-->/" README.md || { echo "Failed to update README for hard stats"; exit 1; }

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update LeetCode stats" || { echo "Failed to commit changes"; exit 1; }
          git push || { echo "Failed to push changes"; exit 1; }
